name: habits
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  hive:
  hive_flutter:
  cloud_firestore: ^4.13.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  persistent_bottom_nav_bar: ^5.0.2

  flutter_svg: ^2.0.8
  firebase_core:
  firebase_storage: ^11.5.2
  firebase_database: ^10.3.5

  url_launcher: ^6.2.1

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  audioplayers: ^5.2.1

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/sounds/

  fonts:
   - family: San Francisco
     fonts:
       - asset: fonts/SF Pro/SFProText-Regular.ttf
       - asset: fonts/SF Pro/SFProText-Light.ttf
       - asset: fonts/SF Pro/SFProText-Bold.ttf
   - family: SansSerif
     fonts:
       - asset: fonts/microsoftsansserif.ttf
   - family: Bahnschrift
     fonts:
       - asset: fonts/Bahnschrift.ttf
